### PR TITLE
264 one off alarms

### LINKED ISSUE #264: Allow one off future alarms
I can set an alarm for a day in the future, but only if I set it to repeat. I should be able to create an alarm that only operates once.

### PR DESCRIPTION
**Pull request by firebirdberlin**
resolves #264

### CODE REVIEW

**Comment by galexmay** [comment]
I agree, particularly in relation to the one-off future alarms

**Comment by galexmay** [comment]
Could someone please explain whether the one-off future alarms are now possible and if so how.

**Comment by firebirdberlin** [comment]
This feature is currently rolled out. It is available since version 2.10.8. We had to stop the rollout for a bugfix. That's why it's taking longer than expected. 

The new feature allows to click on the date (eg. "today"/ "tomorrow") for one-off alarms and to select another date.

**Comment by galexmay** [comment]
Thanks for the reply. I am sorry for being such a newbie. I am not sure what you mean when you say it is currently rolled out, but the rollout is stopped. Are you saying that I can't get it yet? If that is right, do you have any idea when I will be able to get it? If you can tell me that, I will simply wait until then to look again. If I can get that version now, can you please explain how and also what bug I will have to put up with.

**Comment by firebirdberlin** [comment]
We're doing staged rollouts. That means we slowly increase the fraction of users who are able to receive the update. This procedure allows us to identify issues which we didn't capture in the testing phase. In this case we found an unrelated exception on Android 11. We decided to stop the rollout and to resume it with a different version. It's only a matter of a few days until all users are able to update to the most recent version.

**Comment by galexmay** [comment]
Excellent, thanks, I will check back in a week.

**Pull request merged**
